FROM node:lts AS runtime
WORKDIR /app

COPY . .

ARG PUBLIC_API_URL
ARG SITE_ID
ARG PUBLIC_SITE_ID
ARG PUBLIC_API_TOKEN
ARG PUBLIC_MEILISEARCH_HOST
ARG PUBLIC_MEILISEARCH_SEARCH_KEY
ARG PUBLIC_MEILISEARCH_INDEX_NAME
ARG ROOT_DOMAIN
ARG HOSTNAME
ARG FULL_URL
ARG LANG
ARG PUBLIC_RECAPTCHA_SITE_KEY
ARG PUBLIC_IMAGE_URL
ARG PUBLIC_ROOT_DOMAIN
ARG PUBLIC_FULL_URL
ARG SITE_NAME \
ARG PUBLIC_SWETRIX_ID \
ARG IS_PROD

ENV PUBLIC_API_URL=$PUBLIC_API_URL \
    SITE_ID=$SITE_ID \
    PUBLIC_API_TOKEN=$PUBLIC_API_TOKEN \
    PUBLIC_MEILISEARCH_HOST=$PUBLIC_MEILISEARCH_HOST \
    PUBLIC_MEILISEARCH_SEARCH_KEY=$PUBLIC_MEILISEARCH_SEARCH_KEY \
    PUBLIC_MEILISEARCH_INDEX_NAME=$PUBLIC_MEILISEARCH_INDEX_NAME \
    PUBLIC_RECAPTCHA_SITE_KEY=$PUBLIC_RECAPTCHA_SITE_KEY \
    ROOT_DOMAIN=$ROOT_DOMAIN \
    HOSTNAME=$HOSTNAME \
    FULL_URL=$FULL_URL \
    PUBLIC_FULL_URL=$PUBLIC_FULL_URL \
    LANG=$LANG \
    PUBLIC_SITE_ID=$PUBLIC_SITE_ID \
    PUBLIC_IMAGE_URL=$PUBLIC_IMAGE_URL \
    SITE_NAME=$SITE_NAME \
    PUBLIC_ROOT_DOMAIN=$PUBLIC_ROOT_DOMAIN \
    PUBLIC_SWETRIX_ID=$PUBLIC_SWETRIX_ID \
    IS_PROD=$IS_PROD

RUN npm -v
RUN node -v
RUN npm install
RUN npm run build

ENV HOST=0.0.0.0
ENV PORT=4321
EXPOSE 4321
CMD node ./dist/server/entry.mjs