FROM node:lts AS runtime
WORKDIR /app

COPY . .

ARG PUBLIC_API_URL
ARG SITE_ID
ARG API_TOKEN
ARG PUBLIC_MEILISEARCH_HOST
ARG PUBLIC_MEILISEARCH_SEARCH_KEY
ARG PUBLIC_MEILISEARCH_INDEX_NAME
ARG ROOT_DOMAIN
ARG HOSTNAME
ARG FULL_URL
ARG LANG

ENV PUBLIC_API_URL=$PUBLIC_API_URL \
    SITE_ID=$SITE_ID \
    API_TOKEN=$API_TOKEN \
    PUBLIC_MEILISEARCH_HOST=$PUBLIC_MEILISEARCH_HOST \
    PUBLIC_MEILISEARCH_SEARCH_KEY=$PUBLIC_MEILISEARCH_SEARCH_KEY \
    PUBLIC_MEILISEARCH_INDEX_NAME=$PUBLIC_MEILISEARCH_INDEX_NAME \
    ROOT_DOMAIN=$ROOT_DOMAIN \
    HOSTNAME=$HOSTNAME \
    FULL_URL=$FULL_URL \
    LANG=$LANG

RUN npm install
RUN npm run build

ENV HOST=0.0.0.0
ENV PORT=4321
EXPOSE 4321
CMD node ./dist/server/entry.mjs