# Build the strapi image
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--build-arg',
        'output_dist_path=${_OUTPUT_DIST_PATH}',
        '--build-arg',
        'PUBLIC_API_URL=${_PUBLIC_API_URL}',
        '--build-arg',
        'SITE_ID=${_SITE_ID}',
        '--build-arg',
        'PUBLIC_API_TOKEN=${_PUBLIC_API_TOKEN}',
        '--build-arg',
        'PUBLIC_MEILISEARCH_HOST=${_PUBLIC_MEILISEARCH_HOST}',
        '--build-arg',
        'PUBLIC_MEILISEARCH_SEARCH_KEY=${_PUBLIC_MEILISEARCH_SEARCH_KEY}',
        '--build-arg',
        'PUBLIC_MEILISEARCH_INDEX_NAME=${_PUBLIC_MEILISEARCH_INDEX_NAME}',
        '--build-arg',
        'PUBLIC_RECAPTCHA_SITE_KEY=${_PUBLIC_RECAPTCHA_SITE_KEY}',
        '--build-arg',
        'ROOT_DOMAIN=${_ROOT_DOMAIN}',
        '--build-arg',
        'HOSTNAME=${_HOSTNAME}',
        '--build-arg',
        'FULL_URL=${_FULL_URL}',
        '--build-arg',
        'LANG=${_LANG}',
        '--build-arg',
        'PUBLIC_SITE_ID=${_PUBLIC_SITE_ID}',
        '--build-arg',
        'PUBLIC_IMAGE_URL=${_PUBLIC_IMAGE_URL}',
        '--build-arg',
        'PUBLIC_ROOT_DOMAIN=${_PUBLIC_ROOT_DOMAIN}',
        '--build-arg',
        'PUBLIC_FULL_URL=${_PUBLIC_FULL_URL}',
        '--build-arg',
        'PROD=${_PROD}',
        '--build-arg',
        'SITE_NAME=${_SITE_NAME}',
        '--build-arg',
        'MATOMO_SITE_ID=${_MATOMO_SITE_ID}',
        '-t',
        'gcr.io/${_DEPLOY_PROJECT}/${_SERVICE_NAME}',
        '.'
      ]

  # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$_DEPLOY_PROJECT/$_SERVICE_NAME']

  # Deploy container image to Cloud Run

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - 'gcr.io/$_DEPLOY_PROJECT/$_SERVICE_NAME'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'
      - '--project'
      - '$_DEPLOY_PROJECT'
      - '--vpc-connector'
      - '$_VPC_CONNECTOR_NAME'
      - '--vpc-egress'
      - '$_VPC_ACCESS_EGRESS'
      - '--add-cloudsql-instances'
      - '$_SQL_INSTANCE'
      - '--set-env-vars'
      - 'PUBLIC_API_URL=${_PUBLIC_API_URL}'
      - '--set-env-vars'
      - 'SITE_ID=${_SITE_ID}'
      - '--set-env-vars'
      - 'PUBLIC_API_TOKEN=${_PUBLIC_API_TOKEN}'
      - '--set-env-vars'
      - 'PUBLIC_MEILISEARCH_HOST=${_PUBLIC_MEILISEARCH_HOST}'
      - '--set-env-vars'
      - 'PUBLIC_MEILISEARCH_SEARCH_KEY=${_PUBLIC_MEILISEARCH_SEARCH_KEY}'
      - '--set-env-vars'
      - 'PUBLIC_MEILISEARCH_INDEX_NAME=${_PUBLIC_MEILISEARCH_INDEX_NAME}'
      - '--set-env-vars'
      - 'PUBLIC_RECAPTCHA_SITE_KEY=${_PUBLIC_RECAPTCHA_SITE_KEY}'
      - '--set-env-vars'
      - 'ROOT_DOMAIN=${_ROOT_DOMAIN}'
      - '--set-env-vars'
      - 'HOSTNAME=${_HOSTNAME}'
      - '--set-env-vars'
      - 'FULL_URL=${_FULL_URL}'
      - '--set-env-vars'
      - 'LANG=${_LANG}'
      - '--set-env-vars'
      - 'PUBLIC_SITE_ID=${_PUBLIC_SITE_ID}'
      - '--set-env-vars'
      - 'PUBLIC_IMAGE_URL=${_PUBLIC_IMAGE_URL}'
      - '--set-env-vars'
      - 'PUBLIC_ROOT_DOMAIN=${_PUBLIC_ROOT_DOMAIN}'
      - '--set-env-vars'
      - 'PUBLIC_FULL_URL=${_PUBLIC_FULL_URL}'
      - '--set-env-vars'
      - 'PROD=${_PROD}'
      - '--set-env-vars'
      - 'SITE_NAME=${_SITE_NAME}'
      - '--set-env-vars'
      - 'MATOMO_SITE_ID=${_MATOMO_SITE_ID}'

substitutions:
  _OUTPUT_DIST_PATH: '/'
  _NODE_ENV: 'production'
  _DEPLOY_PROJECT: ''
  _SERVICE_NAME: ''
  _REGION: 'europe-west8'
  _AUTH_OPTION: '--allow-unauthenticated'
  _VPC_CONNECTOR_NAME: ''
  _VPC_ACCESS_EGRESS: 'private-ranges-only'
  _PUBLIC_API_URL: ''
  _SITE_ID: ''
  _PUBLIC_API_TOKEN: ''
  _PUBLIC_MEILISEARCH_HOST: ''
  _PUBLIC_MEILISEARCH_SEARCH_KEY: ''
  _PUBLIC_MEILISEARCH_INDEX_NAME: ''
  _ROOT_DOMAIN: ''
  _HOSTNAME: ''
  _FULL_URL: ''
  _LANG: ''
  _PUBLIC_RECAPTCHA_SITE_KEY: ''
  _PUBLIC_IMAGE_URL: ''
  _PUBLIC_ROOT_DOMAIN: ''
  _PUBLIC_FULL_URL: ''
  _SITE_NAME: ''
  _PROD: 'false'
  _MATOMO_SITE_ID: ''

timeout: 2700s
